package game

enum class GamePhase {
    PAUSE,
    PLAY,
    MAIN_MENU,
    MAIN_MENU_SELECT_PLAYERS,
    NEW_GAME_INTRO,
    PLAYERS_PICK_SHIELDS,
    NONE,
    PLAYERS_TURN,
    PLAYERS_TURN_FIRED,
    PLAYERS_TURN_FIRED_WAIT_STABILIZE,
    PLAYERS_TURN_ENDING,
    PLAYERS_TURN_END,
    PLAYERS_TURN_JUMPED,
    PLAYERS_TURN_AIMING,
    PLAYERS_TURN_POWERING,
    PLAYERS_WATCH_DAMAGE_DEALT_INTRO,
    PLAYERS_WATCH_DAMAGE_DEALT,
    END_ROUND

}
